package model;

public class User {
    private final int userId;
    private final String username;
    private final String password;
    private final String email;
    private final Role role;

    public User(int userId, String username, String password, String email, Role role) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.email = email;
        this.role = role;
    }

    // Constructor for new users (without ID, auto-generated by DB)
    public User(String username, String password, String email, Role role) {
        this(-1, username, password, email, role);
    }

    public int getUserId() { return userId; }
    public String getUsername() { return username; }
    public String getPassword() { return password; }
    public String getEmail() { return email; }
    public Role getRole() { return role; }
}